<?php

/**
 * @package JFusion
 * @subpackage Models
 * @version 1.0.7
 * @author JFusion development team
 * @copyright Copyright (C) 2008 JFusion. All rights reserved.
 * @license http://www.gnu.org/copyleft/gpl.html GNU/GPL
 */

// no direct access
defined('_JEXEC' ) or die('Restricted access' );

/**
* Abstract interface for all JFusion functions that are accessed through the Joomla front-end
* @package JFusion
*/
class JFusionPublic{

    /**
     * returns the name of this JFusion plugin
     * @return string name of current JFusion plugin
     */
    function getJname()
    {
        return '';
    }

    /**
     * gets the visual html output from the plugin
     */
    function & getBuffer()
    {
    }

    /**
     * function that parses the HTML body and fixes up URLs and form actions
     * @param string the HTML body output generated by getBuffer()
     * @param string $baseURL the base joomla URL to add variables to
     * @param string $fullURL the full URL to the current page
     * @param string $integratedURL the URL to the integrated software
     * @return object userinfo Object containing the user information
     */
    function parseBody(&$buffer, $baseURL, $fullURL, $integratedURL)
    {
    }

    /**
     * function that parses the HTML header and fixes up URLs
     * @param string $buffer the output generated by getBuffer()
     * @param string $baseURL the base joomla URL to add variables to
     * @param string $fullURL the full URL to the current page
     * @param string $integratedURL the URL to the integrated software
     * @return object userinfo Object containing the user information
     */
    function parseHeader(&$buffer, $baseURL, $fullURL, $integratedURL)
    {
    }

     /**
     * Returns the registration URL for the integrated software
     * @return string registration URL
     */
    function getRegistrationURL()
    {
        return '';
    }

     /**
     * Returns the lost password URL for the integrated software
     * @return string lost password URL
     */
    function getLostPasswordURL()
    {
        return '';
    }

     /**
     * Returns the lost username URL for the integrated software
     * @return string lost username URL
     */
    function getLostUsernameURL()
    {
        return '';
    }




}



